apiVersion: v1
kind: Service
metadata:
  name: aks-request-frontend
  labels:
    app: aks-request
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: aks-request
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server
