apiVersion: v1
kind: Service
metadata:
  name: aks-request-backend
  labels:
    app: aks-request
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: aks-request
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
